version: "3.3"

services:
    bootstrap:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        command: ./.docker/bootstrap.sh

    api:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - "3000:3000"